apiVersion: v1
kind: Service
metadata:
  name: ow-mysql
  namespace: default
  labels:
    app: ow-mysql
    service: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: 
    service: mysql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ow-mysql
  labels:
    app: ow-mysql
    service: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ow-mysql
      service: mysql
  template:
    metadata:
      labels:
        app: ow-mysql
        service: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/Sao_Paulo"
            - name: MYSQL_ROOT_PASSWORD
              value: "owpass"
          ports:
            - containerPort: 3306