openapi: "3.0.0"
info:
  version: 1.0.0
  title: "Desafio Backend"
  description: "Esta é uma api de Teste"
  license:
    name: MIT
  contact:
    name: J.S.Júnior
    email: j.s.junior@live.com
servers:
  - url: "https://desafiobackend.local/"
    description: "Api de Dev"
tags:
  - name: users
    description: "Responsável por `listagem`, `listar um`, `apagar`, `mudar saldo`, `ver saldos`"
  - name: auth
    description: "Responsável por `criar usuário`, `logar usuário`"
  - name: movements
    description: "Responsável por `criar movimento`, `listar`, `exportar`, `apagar`"

paths:
  /users:
    get:
      tags:
        - users
      summary: Lista todos os usuários
      description: 'Lista todos os usuários'
      responses:
        '200':
          description: successful operation
        '204':
          description: No Content
        '400':
          description: Bad request
  /users/{idUser}:
    get:
      tags:
        - users
      summary: Lista um usuário
      description: 'Lista um usuário'
      responses:
        '200':
          description: successful operation
        '204':
          description: No Content
        '400':
          description: Bad request
  /users/{id_user}:
    delete:
      tags:
        - users
      summary: Apaga um usuário
      description: 'Apaga um usuário'
      responses:
        '200':
          description: successful operation
        '204':
          description: No Content
        '400':
          description: Bad request
  /users/{id_user}/change-balance:
    put:
      tags:
        - users
      summary: Atualiza o saldo inicial do usuário
      description: 'Atualiza o saldo inicial do usuário'
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                value:
                  type: number
      responses:
        '200':
          description: successful operation
        '204':
          description: No Content
        '400':
          description: Bad request
  /users/{id_user}/balance:
    put:
      tags:
        - users
      summary: Exibe os saldos do usuário
      description: 'Exibe os saldos do usuário'
      responses:
        '200':
          description: successful operation
        '204':
          description: No Content
        '400':
          description: Bad request
  /auth/login:
      post:
        tags:
          - auth
        summary: Autentica o usuário
        description: 'Autentica o usuário'
        requestBody:
          content:
            'application/json':
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
        responses:
          '200':
            description: successful operation
          '401':
            description: Unauthorized
          '400':
            description: Bad request
  /auth/signin:
    post:
      tags:
        - auth
      summary: Cadastra um usuário
      description: 'Cadastra um usuário'
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                birthday:
                  type: string
                  example: "9999-99-99"
                opening_balance:
                  type: number
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
  /movements:
    post:
      tags:
        - movements
      summary: Adiciona um movimento ao usuário
      description: 'Adiciona um movimento ao usuário'
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                user_id:
                  type: number
                type:
                  type: string
                  example: "debit|credit|reversal"
                value:
                  type: number
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
  /movements/user/{user_id}:
    get:
      tags:
        - movements
      summary: Lista as movimentações do usuário
      description: 'Lista as movimentações do usuário'
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
  /movements/export/user/{user_id}:
      post:
        tags:
          - movements
        summary: Exporta em CSV as movimentações do usuário
        description: 'Exporta em CSV as movimentações do usuário'
        requestBody:
          content:
            'application/json':
              schema:
                type: object
                properties:
                  last_thirty_days:
                    type: boolean
                  month:
                    type: string
                    example: "9999-99"
                  all:
                    type: boolean
        responses:
          '200':
            description: successful operation
          '400':
            description: Bad request
  /movements/{movement_id}/user/{user_id}:
    delete:
      tags:
        - movements
      summary: Apaga uma movimentação do usuário
      description: 'Apaga uma movimentação do usuário'
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
